version: 2 
jobs: 
  build: 
    docker: 
      - image: circleci/openjdk:8u212-jdk-stretch
        command: ["/bin/bash"]
    steps: 
      - run:
          name: Checkout GeoTools, GeoWebCache and GeoServer
          command: |
            echo "Preparing git ssh checkouts"
            mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            echo "Checking out GeoTools"
            mkdir geotools
            git clone git@github.com:geotools/geotools.git geotools
            echo "Checking out GeoWebCache"
            mkdir geowebcache
            git clone git@github.com:GeoWebCache/geowebcache.git geowebcache
            echo "Checking out GeoServer"
            mkdir geoserver
            git clone git@github.com:geoserver/geoserver.git geoserver

      - run:
          name: Generate cache key
          command: |
            find geotools geowebcache geoserver -name "pom.xml" | sort | xargs md5sum > /tmp/checksum.txt
           
      - restore_cache:
          key: gt_gwc_gs-{{ checksum "/tmp/checksum.txt" }}

      - run:
          name: Build GeoTools (no tests, prepare fresh artifacts)
          command: mvn -f geotools/pom.xml install dependency:resolve-plugins dependency:go-offline -DargLine="-Xmx256m -XX:+UseStringDeduplication -XX:+UseG1GC" -Dall -Dfmt.skip=true -DskipTests

      - run:
          name: Build GeoWebCache with tests
          command: |
            mvn -f geowebcache/geowebcache/pom.xml install dependency:resolve-plugins dependency:go-offline -nsu -DargLine="-Xmx256m -XX:+UseStringDeduplication -XX:+UseG1GC" -Dfmt.skip=true -DskipTests
            mvn -f geowebcache/geowebcache/pom.xml test -o -T2 -DargLine="-Xmx128m" -Dfmt.skip=true

      - run:
          name: Build GeoServer with tests (and community modules without)
          command: |
            mvn -f geoserver/src/pom.xml install dependency:resolve-plugins dependency:go-offline -nsu -DargLine="-Xmx256m -XX:+UseStringDeduplication -XX:+UseG1GC" -Prelease,communityRelease -Dfmt.skip=true -DskipTests
            mvn -f geoserver/src/pom.xml test -T2 -o -DargLine="-Xmx128m" -Prelease -Dfmt.skip=true
            mvn -f geoserver/src/community/pom.xml test -o -T2 -DargLine="-Xmx128m" -PcommunityRelease -Dfmt.skip=true -DskipTests

      - run:
          name: Cleanup repository (remove snapshots)
          command: |
            rm -rf ~/.m2/repository/org/geotools
            rm -rf ~/.m2/repository/org/geowebcache
            rm -rf ~/.m2/repository/org/geoserver

      - save_cache:
          key: gt_gwc_gs-{{ checksum "/tmp/checksum.txt" }}
          paths:
            - ~/.m2/repository