version: 2 
jobs: # a collection of steps
  build: 
    docker: 
      - image: circleci/openjdk:8u212-jdk-stretch
        command: ["/bin/bash"]
    steps: 
      - run:
          name: Avoid hosts unknown for github
          command: |
            mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            mkdir ~/geotools
            git clone git@github.com:geotools/geotools.git ~/geowebcache
            cd ~/geotols
            mvn install -DargLine="-Xmx256m" -Dall -Dfmt.skip=true -DskipTests # run the build and prepare fresh geotools artifacts
            mkdir ~/geowebcache
            git clone git@github.com:GeoWebCache/geowebcache.git ~/geowebcache
            cd ~/geowebcache
            mvn install -DargLine="-Xmx256m" -Dfmt.skip=true
